title: ScanGov
description: Government digital experience monitor
url: https://scangov.org
org: Civic Hacking Agency
org-url: https://civichackingagency.org
repo: https://github.com/civichackingagency/scangov
rss: https://docs.scangov.org/feed.xml

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  
# Social

github-url: https://github.com/civichackingagency
linkedin-url: https://www.linkedin.com/company/civic-hacking-agency
twitter-url: https://twitter.com/civic_hacking

twitter-username: civic_hacking
twitter: "@civichacking"

# Date/time
date: "%B %-d, %Y"
timezone: America/Los_Angeles

# Collections
collections:
  pages:
    output: true
    permalink: :title

# Defaults
defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "page"
      parent: ""
      short: "true"

# Exclude
exclude:
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME